docs: add WSL setup instructions
AlaskaAirlines/WC-Generator pull request #107
Opened 2021-04-27 23:51 UTC by geoffrich

# Alaska Airlines Pull Request

This adds setup instructions for WSL.

Reference: https://github.com/AlaskaAirlines/WC-Generator/issues/89

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [x] New capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-04-30 00:01 UTC, blackfalcon requested changes

2021-04-30 00:01 UTC, blackfalcon commented on docs/devSetup.md
> +In a separate terminal, run `npm run serve` to serve the component's demo page. CTRL+click on the displayed URL to open the demo page in your web browser. You should see the auro-button demo page.
```suggestion
In a separate terminal/shell, run `npm run serve` to serve the component's demo page. `CTRL+click` on the displayed URL to open the demo page in your web browser. You should see the `auro-button` demo page.
```

2021-04-30 00:01 UTC, blackfalcon commented on docs/devSetup.md
> +You need to configure your git name and email in WSL. Run the following in the terminal:
```suggestion
You need to configure your Git name and email in WSL. Run the following in the terminal:
```

2021-04-30 15:34 UTC, geoffrich commented on docs/devSetup.md
> +After WSL is installed, you can open the WSL terminal by running the `wsl` command or opening Ubuntu from the start menu. WSL does not have a GUI you can interact with -- everything is done from the
I was having trouble finding a high-quality one so I skipped it. Looks like the one you linked is more for bash scripting, so not super relevant to moving around the terminal. What do you think about [this one](https://www.git-tower.com/blog/command-line-cheat-sheet/)?

2021-04-30 15:51 UTC, geoffrich commented on docs/devSetup.md
> +You need to install several dependencies on WSL so that you can develop Auro. Even if you have these installed on your main Windows machine, you still need to install them in WSL.
I'm trying to draw a distinction here between developing with Auro (i.e. consuming the components in a React/Svelte/whatever project) and developing Auro components themselves. It's possible to consume the components without WSL. Do you think "with Auro" is clear enough?

2021-04-30 15:53 UTC, geoffrich commented on docs/devSetup.md
> +Inside VS Code, open the integrated terminal with CTRL+SHIFT+`. Run the following commands to install dependencies and build the component.
Fixed. Had to use double-backticks on the shortcut, since it's actually referring to the backtick key.

2021-04-30 15:54 UTC, geoffrich commented
A couple Qs on your suggestions, but I committed the ones I agreed with. Let me know if you want me to squash everything into a single commit when we wrap up your other comments.

2021-04-30 21:46 UTC, blackfalcon commented on docs/devSetup.md
> +You need to install several dependencies on WSL so that you can develop Auro. Even if you have these installed on your main Windows machine, you still need to install them in WSL.
I think so. 

> ... develop with Auro.

Maybe be more direct then

> ... develop an Auro component.

2021-05-03 04:34 UTC, blackfalcon approved these changes

2021-05-03 04:34 UTC, merged

2021-05-17 15:20 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/wc-generator/v/3.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/WC-Generator/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: