Jbaker/generate docs refactor
AlaskaAirlines/WC-Generator pull request #297
Opened 2021-12-21 08:28 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Summary:

This change updates the static doc partials and makes the template docs compile using the remote resources that now exist on the server.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-12-21 17:56 UTC, blackfalcon requested changes
When running a build, the root `./README` file is never created. This is consistent with `npm test`, `npm run build:complete` for both labs and standard repo.

2021-12-21 18:00 UTC, blackfalcon requested changes

2021-12-21 18:00 UTC, blackfalcon commented on template/scripts/generateDocs.js
> +
remove line

2021-12-21 18:00 UTC, blackfalcon commented on template/scripts/generateDocs.js
> +}
```suggestion
if (!fs.existsSync(dir)){
  fs.mkdirSync(dir);
};
```

2021-12-21 18:00 UTC, blackfalcon commented on template/scripts/generateDocs.js
> +// Compile `./docTemplates/README.md` -> `./README.md`
Is this commented out code or a comment of the code? 

If a comment of the code, please use the `/** */ syntax.

2021-12-21 18:00 UTC, blackfalcon commented on template/scripts/generateDocs.js
> +const readmeTemplateUrl = 'https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator/master/componentDocs/README.md'
There are missing semi-colons, please address where needed.

2021-12-22 21:00 UTC, blackfalcon commented
Thar be the issue! 

```
FILE NOT FOUND /Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md
✔ demo/demo.md Updated
 Transforms run
  ⁕ FILE:src=./description.md 
  ⁕ FILE:src=./useCases.md 
  ⁕ FILE:src=./../../apiExamples/basic.html 
  ⁕ CODE:src=./../../apiExamples/basic.html 

Finished compiling demo documentation.
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.FILE (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/transforms/file.js:15:25)
    at updateContents (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/updateContents.js:24:56)
    at processFile (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/processFile.js:101:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/index.js:33:15
    at async Promise.all (index 0)
    at async markdownMagic (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/index.js:37:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md'
}
./auro-test (main *) $ 
```

2021-12-22 21:12 UTC, blackfalcon approved these changes

2021-12-22 21:13 UTC, jason-capsule42 commented
> Thar be the issue!
> 
> ```
> FILE NOT FOUND /Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md
> ✔ demo/demo.md Updated
>  Transforms run
>   ⁕ FILE:src=./description.md 
>   ⁕ FILE:src=./useCases.md 
>   ⁕ FILE:src=./../../apiExamples/basic.html 
>   ⁕ CODE:src=./../../apiExamples/basic.html 
> 
> Finished compiling demo documentation.
> node:fs:585
>   handleErrorFromBinding(ctx);
>   ^
> 
> Error: ENOENT: no such file or directory, open '/Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md'
>     at Object.openSync (node:fs:585:3)
>     at Object.readFileSync (node:fs:453:35)
>     at Object.FILE (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/transforms/file.js:15:25)
>     at updateContents (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/updateContents.js:24:56)
>     at processFile (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/lib/processFile.js:101:32)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async /Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/index.js:33:15
>     at async Promise.all (index 0)
>     at async markdownMagic (/Users/dalesande/src/auro/auro-test/node_modules/markdown-magic/index.js:37:18) {
>   errno: -2,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: '/Users/dalesande/src/auro/auro-test/docTemplates/partials/browserSupport.md'
> }
> ./auro-test (main *) $ 
> ```

Issue here is that the the generateDpcs script imports the readme.md template from the server before compiling it. The current version on the server doesnt use the static resources it wants to use local resources. As soon as this is actually on the master branch it will work correctly.

2021-12-22 21:13 UTC, merged

2021-12-22 21:16 UTC, blackfalcon commented
:tada: This PR is included in version 3.13.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/wc-generator/v/3.13.0)
- [GitHub release](https://github.com/AlaskaAirlines/WC-Generator/releases/tag/v3.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: