feat(docs): generate docs handles dynamic npm, namespace and name
AlaskaAirlines/WC-Generator pull request #301
Opened 2021-12-27 21:52 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #300

## Summary:

This change improves the generateDocs.js script achieving two goals:
1. Make the doc generate dynamically replace [npm], [namespace] and [name] variables in md docs (extensible)
1. General code cleanup since this script was starting to get fairly complex including wrapping code sections into semantic functions

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-12-28 01:39 UTC, blackfalcon requested changes

2021-12-28 01:39 UTC, blackfalcon commented on template/scripts/generateDocs.js
> +  result = result.replace(/\[npm]/g, nameExtractionData.npm);
```
Finished compiling demo documentation.
/Users/dalesande/src/auro/auro-test/scripts/generateDocs.js:47
  result = result.replace(/\@aurodesignsystem/g, nameExtractionData.npm);
                  ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at formatTemplateFileContents (/Users/dalesande/src/auro/auro-test/scripts/generateDocs.js:47:19)
    at ReadFileContext.callback (/Users/dalesande/src/auro/auro-test/scripts/generateDocs.js:104:5)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)
ERROR: "build:markdownDocs" exited with 1.
```

2022-01-03 23:45 UTC, Dayna-A approved these changes
Thanks for the detailed explanation session.
This is great! My only PR wish is for a future iteration with some good star wars lorum ipsum for the han solo component. [a la forcemipsum](https://forcemipsum.com/)

I would absolutely love to see the api Examples code turned into a api-example component that generates the demo and the code snippet instead of repeating that code everywhere @blackfalcon & @jason-capsule42 !

2022-01-03 23:50 UTC, merged

2022-01-03 23:52 UTC, blackfalcon commented
:tada: This PR is included in version 3.14.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/wc-generator/v/3.14.0)
- [GitHub release](https://github.com/AlaskaAirlines/WC-Generator/releases/tag/v3.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: